# Generated by Django 5.0 on 2023-12-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_title_delete_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='titles',
        ),
    ]
