# Generated by Django 5.0 on 2023-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='components',
            field=models.TextField(blank=True, default='pustoy'),
        ),
        migrations.AlterField(
            model_name='category',
            name='titles',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='title'),
        ),
    ]
